AWSTemplateFormatVersion: '2010-09-09'
Description: 'Bastion host para teste do ambiente'
Parameters:
  SubnetPublic:
    Type: String
    Description: ID Subnet
    Default : subnet-0c4f3a37f1ed72b3c
  VPCID:
    Type: String
    Description: ID VPC
    Default : vpc-0d39fdf3ab55dee88
  AMIID:
    Type: String
    Description: ID da Imagem para criar o servidor 
    Default: ami-0ed417ef057137c75   
  KeyName:
    Description: EC2 KeyPair
    Type: String
    Default: grupopll-key-v2
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t3.micro
    AllowedValues:
    - t3.nano
    - t3.micro
    - t3.small
    - t3.medium
    - t3.large
    ConstraintDescription: must be a valid EC2 instance type.
  SSHLocation:
    Description: O Range de IP que ira conectar no EC2
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType:
        Ref: InstanceType
      SecurityGroupIds: 
        - !GetAtt "InstanceSecurityGroup.GroupId"
      SubnetId: 
        Ref: SubnetPublic
      KeyName:
        Ref: KeyName
      ImageId:
        Ref: AMIID
      Tags:
        -
          Key: Name
          Value: Bastion
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "rdp-group"
      VpcId: !Ref VPCID
      GroupDescription: Enable RDP access via port 3389
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '3389'
        ToPort: '3389'
        CidrIp:
          Ref: SSHLocation
Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value:
      Ref: EC2Instance
  AZ:
    Description: Availability Zone of the newly created EC2 instance
    Value:
      Fn::GetAtt:
      - EC2Instance
      - AvailabilityZone
  PublicDNS:
    Description: Public DNSName of the newly created EC2 instance
    Value:
      Fn::GetAtt:
      - EC2Instance
      - PublicDnsName
  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value:
      Fn::GetAtt:
      - EC2Instance
      - PublicIp